name: flutter_from_zero
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  get_cli: ^1.8.4
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dio: ^5.3.3
  flutter_easyloading: ^3.0.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

